export default {
  SET_SEARCH_INPUTS: "SET_SEARCH_INPUTS",
  SET_AUTH: "SET_AUTH",
  SET_ONE_WAY_TICKETS: "SET_ONE_WAY_TICKETS",
  SET_ROUND_TRIP_TICKETS: "SET_ROUND_TRIP_TICKETS",
  SET_RESULTS: "SET_RESULTS",
};
